---

# Create Staging Folder
- name: Create Staging Folder
  file:
    path: /build-artifacts/
    state: directory

# Download and install Endgame package from s3 bucket when endgame_s3_bucket is set
- name: Ensure botocore and boto3 modules are installed
  pip:
    name:         [ "boto3", "botocore"]
    extra_args:   "--user"
  when: endgame_s3_bucket != ""

- name: Download from s3 bucket when endgame_s3_bucket is set
  aws_s3:
    bucket: "{{ endgame_s3_bucket }}"
    object: "/{{ endgame_s3_prefix }}/{{ item }}"
    dest: "/build-artifacts/{{ item }}"
    mode: get
  with_items:
    - "{{ endgame_config }}"
    - "{{ endgame_installer }}"
  when: endgame_s3_bucket != ""

- name: Grant execution permission
  file:
    path: /build-artifacts/{{ endgame_installer }}
    state: touch
    mode: u+x

#- name: run endgame installer
#  shell: /build-artifacts/{{ endgame_installer }} -k {{ endgame_apikey }} -c /build-artifacts/{{ endgame_config }}
#  become: yes
#  args:
#    creates: /usr/sbin/esensor
