---

# Create Staging Folder
- name: Create Staging Folder
  file:
    path: /build-artifacts/
    state: directory

- name: Copy installer files to remote server
  copy:
    src: "{{ role_path }}/files/"
    dest: "/build-artifacts/"

- name: Grant execution permission
  file:
    path: /build-artifacts/
    mode: u+x
    recurse: yes