---

# Create Staging Folder
- name: Create Staging Folder
  file:
    path: /build-artifacts/
    state: directory

- shell: pip list
  register: pip_list

- name: Ensure boto3 module is installed
  pip:
    name: "boto3"
    extra_args: "--user"
  when: '"boto3" is not in pip_list.stdout'

- name: Ensure botocore module is installed
  pip:
    name: "botocore"
    extra_args: "--user"
  when: '"botocore" is not in pip_list.stdout'

- name: Download from s3 bucket when endgame_s3_bucket is set
  aws_s3:
    bucket: "{{ endgame_s3_bucket }}"
    object: "/{{ endgame_s3_prefix }}/{{ item }}"
    dest: "/build-artifacts/{{ item }}"
    mode: get
  with_items:
    - "{{ endgame_config }}"
    - "{{ endgame_installer }}"

- name: Grant execution permission
  file:
    path: /build-artifacts/{{ endgame_installer }}
    state: touch
    mode: u+x

#- name: run endgame installer
#  shell: /build-artifacts/{{ endgame_installer }} -k {{ endgame_apikey }} -c /build-artifacts/{{ endgame_config }}
#  become: yes
#  args:
#    creates: /usr/sbin/esensor
