---

# Create Staging Folder
- name: Create Staging Folder
  file:
    path: /build-artifacts/
    state: directory

- name: Copy installer files to remote server
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/build-artifacts/{{ item }}"
  with_items:
  - "{{ endgame_package }}"
  - "{{ endgame_config }}"

- name: Grant execution permission
  file:
    path: "/build-artifacts/{{ endgame_package }}"
    mode: u+x