---

- set_fact:
    endgame_apikey:  "{{ secret_text | json_query('endgame_apikey') }}" 

- name: RedHat
  set_fact:
    package_folder: rpm
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Ubuntu and debian
  set_fact:
    package_folder: deb
  when: ansible_facts['os_family']|lower == 'debian'

- name: Windows Server and Workstation
  set_fact:
    package_folder: win
  when: ansible_facts['os_family']|lower == 'windows'

- name: Check if installer exists
  stat:
    path: "{{ role_path }}/files/{{ endgame_installer_file [package_folder] }}"
  register: stat_result
  delegate_to: localhost
  become: false

- name: Download Binaries from S3 
  aws_s3:
    bucket: sectools-installation-artifacts
    object: "{{ package_folder }}/{{ item }}"
    dest: "{{ role_path }}/files/{{ item }}"
    mode: get
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    aws_security_token: "{{ session_token }}"
  when: not stat_result.stat.exists
  with_items:
  - "{{ endgame_installer_file[package_folder] }}"
  - "{{ endgame_config_file }}"
  delegate_to: localhost
  become: false

- name: RedHat
  include_tasks: linux-install.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Ubuntu and debian
  include_tasks: linux-install.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Windows Server and Workstation
  include_tasks: win-install.yml
  when: ansible_facts['os_family']|lower == 'windows'
  