---
- name: copy endgame files to target
  copy: src={{ item.src }} dest=/tmp/{{ item.dest }} mode=0770
  with_items:
    - { src: "{{ endgame_config }}", dest: "{{ endgame_config }}" }
    
# Download and install Endgame package from s3 bucket when endgame_s3_bucket is set

- name: Ensure botocore and boto3 modules are installed
  pip:
    name:         [ "boto3", "botocore"]
    extra_args:   "--user"
  when: endgame_s3_bucket != ""

- name: Download from s3 bucket when endgame_s3_bucket is set
  aws_s3:
    bucket: "{{ endgame_s3_bucket }}"
    object: "{{ endgame_s3_prefix }}/{{ endgame_installer }}"
    dest: /tmp/{{ endgame_installer }}
    mode: get
  when: endgame_s3_bucket != ""

- name: run endgame installer
  shell: /tmp/{{ endgame_installer }} -k {{ endgame_apikey }} -c /tmp/{{ endgame_config }}
  become: yes
  args:
    creates: /usr/sbin/esensor
