---
# Create Staging Folder
- name: Create Staging Folder
  file:
    path: c:\build-artifacts
    state: directory

- name: Copy installer files to remote server
  win_copy:
    src: "{{ role_path }}/files/"
    dest: c:\build-artifacts\

#- name: Run EndGame with configuration
#  win_command: '"C:\Temp\EndgameAgent\{{endgame_installer}}" -k {{ endgame_apikey }} -c "C:\Temp\EndgameAgent\{{ endgame_config }}" -l C:\Temp\error.log'
